/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaForm;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author tharoth
 */
public class EditInformation extends javax.swing.JFrame {

    /**
     * Creates new form EditInformation
     */
    public EditInformation() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        rdOther = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtIdEdit = new javax.swing.JTextField();
        txtNameEdit = new javax.swing.JTextField();
        txtAddressEdit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInformation = new javax.swing.JTable();
        tblDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setText("Address");

        buttonGroup1.add(rdMale);
        rdMale.setText("Male");

        buttonGroup1.add(rdFemale);
        rdFemale.setText("Female");

        buttonGroup1.add(rdOther);
        rdOther.setText("Other");

        jLabel4.setText("Gender");

        txtIdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEditActionPerformed(evt);
            }
        });
        txtIdEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdEditKeyTyped(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        btnBack.setBackground(java.awt.Color.darkGray);
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(java.awt.Color.darkGray);
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Address"
            }
        ));
        tblInformation.setUpdateSelectionOnSort(false);
        tblInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInformationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInformation);

        tblDelete.setText("Delete");
        tblDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdEdit)
                            .addComponent(txtNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdMale)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddressEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdFemale)
                                .addGap(18, 18, 18)
                                .addComponent(rdOther)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack)
                    .addComponent(btnUpdate))
                .addGap(49, 49, 49))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnUpdate))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tblDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdMale)
                    .addComponent(rdFemale)
                    .addComponent(rdOther))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtAddressEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEditActionPerformed

    private void txtIdEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdEditKeyTyped
        // TODO add your handling code here:
        char id= evt.getKeyChar();
        if(!(Character.isDigit(id))){
            evt.consume();
        }
    }//GEN-LAST:event_txtIdEditKeyTyped

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblUpdateModel = (DefaultTableModel) tblInformation.getModel();
        
        if(tblInformation.getSelectedRowCount()==1){
        
            String id = txtIdEdit.getText();
            String name = txtNameEdit.getText();
            String gender="";
            String address = txtAddressEdit.getText();

            if (rdMale.isSelected()){
                gender="Male";
            }
            else if (rdFemale.isSelected()){
                gender="Female";
            }
            else {
                gender="Gay as FUCK!!";
            }
            tblInformation.setValueAt(id, tblInformation.getSelectedRow(), 0);
            tblInformation.setValueAt(name, tblInformation.getSelectedRow(), 1);
            tblInformation.setValueAt(gender, tblInformation.getSelectedRow(), 2);
            tblInformation.setValueAt(address, tblInformation.getSelectedRow(), 3);
            
            
            JOptionPane.showMessageDialog(this, "Update success!");
            
            txtIdEdit.setText("");
            txtNameEdit.setText("");
            rdMale.setSelected(false);
            rdFemale.setSelected(false);
            rdOther.setSelected(false);
            txtAddressEdit.setText("");
        }
        else{
            if(tblInformation.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Empty table.");
            }
            else
                JOptionPane.showMessageDialog(this, "Please select to update.");
        }    
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        TableModel tblModEdit = tblInformation.getModel();
        int count = tblModEdit.getRowCount();
        Object[] row = new Object[4];
        
        Information infoForm = new Information();
        DefaultTableModel mod2 = (DefaultTableModel) infoForm.tblInformation.getModel();
        for (int i =0; i <count; i++){
            
            row[0] =tblModEdit.getValueAt(i, 0);
            row[1] =tblModEdit.getValueAt(i, 1);
            row[2] =tblModEdit.getValueAt(i, 2);
            row[3] =tblModEdit.getValueAt(i, 3);
            
            mod2.addRow(row);
        }
        infoForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInformationMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblUpdateModel = (DefaultTableModel) tblInformation.getModel();
        
        String id = tblUpdateModel.getValueAt(tblInformation.getSelectedRow(), 0).toString();
        String name = tblUpdateModel.getValueAt(tblInformation.getSelectedRow(), 1).toString();
        String gender = tblUpdateModel.getValueAt(tblInformation.getSelectedRow(), 2).toString();
        String address = tblUpdateModel.getValueAt(tblInformation.getSelectedRow(), 3).toString();
        
        txtIdEdit.setText(id);
        txtNameEdit.setText(name);
        txtAddressEdit.setText(address);
        
        if(gender.equals("Male")){
            rdMale.setSelected(true);
        }
        else if (gender.equals("Female")){
            rdFemale.setSelected(true);
        }
        else if (gender.equals("Gay as FUCK!!")){
            rdOther.setSelected(true);
        }
    }//GEN-LAST:event_tblInformationMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void tblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblDeleteActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modDelete = (DefaultTableModel) tblInformation.getModel();
        
        if (tblInformation.getSelectedRowCount() ==1){
            modDelete.removeRow(tblInformation.getSelectedRow());
        }
        else{
            if(tblInformation.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Empty table.");
            }
            else
                JOptionPane.showMessageDialog(this, "Please select.");
        }
    }//GEN-LAST:event_tblDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
            UIManager.put("Button.arc", 10);
            UIManager.put( "Component.arc", 10 );
            UIManager.put( "ProgressBar.arc", 10 );
            UIManager.put( "TextComponent.arc", 10 );
            
        } catch (Exception e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton rdFemale;
    public javax.swing.JRadioButton rdMale;
    public javax.swing.JRadioButton rdOther;
    private javax.swing.JButton tblDelete;
    public javax.swing.JTable tblInformation;
    public javax.swing.JTextField txtAddressEdit;
    public javax.swing.JTextField txtIdEdit;
    public javax.swing.JTextField txtNameEdit;
    // End of variables declaration//GEN-END:variables
}
